### ISSUE TITLE
Handle device rotation

### ISSUE THREAD

**Issue by animaonline** [sudeepjaiswal/ASJCollectionViewFillLayout#2]

**Comment by sdpjswl** [comment]
I'll look into it.

**Comment by sdpjswl** [comment]
Hey @animaonline, I've fixed this issue in [version 1.0](https://github.com/sudeepjaiswal/ASJCollectionViewFillLayout/releases/tag/1.0). You may update your pod to reflect the change. Thanks for bringing the issue up, it had completely slipped my mind.
